/**
 * This code was generated by Builder.io.
 */
import * as React from "react";
import styled from "styled-components";

function MyComponent(props) {
  return (
    <Div>
      <Div2>
        <Div3>12.00</Div3>
        <Div4>
          <Img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/0d91cc1b-dba7-40e8-8d1c-c7dc64cc27a0?"
          />
          <Img2
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/6ed09dba-a0db-4d51-93e1-f0388ad14888?"
          />
          <Img3
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/953bf984-8241-4442-8e57-f6f89a5ea048?"
          />
        </Div4>
      </Div2>
      <Div5>Add Employee Details</Div5>
      <Div6>
        <Div7>
          <Img4
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/10dc3e33-edcd-4282-ba0e-a3d5a0c351bd?"
          />
          <Div8>Joseph Manadan</Div8>
        </Div7>
      </Div6>
      <Div9>
        <Div10>
          <Img5
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/9dcddc67-1f8b-4501-b73c-e2e73352db33?"
          />
          <Div11>Flutter Developer</Div11>
        </Div10>
        <Img6
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/acd5da87-a935-443a-9bc5-53463ae34a92?"
        />
      </Div9>
      <Div12>
        <Div13>
          <Img7
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/fd942cf7-1bbb-44d7-b644-2f8eb3364131?"
          />
          <Div14>Today</Div14>
        </Div13>
        <Img8
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/790eb27a-d8e4-49f2-81d6-2106a539d42f?"
        />
        <Div15>
          <Img9
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/7ba0fb64-5248-4a2c-897f-df8e20f539d3?"
          />
          <Div16>No date</Div16>
        </Div15>
      </Div12>
      <Div17>
        <Div18>Cancel</Div18>
        <Div19>
          <Div20>Save</Div20>
        </Div19>
      </Div17>
    </Div>
  );
}

const Div = styled.div`
  background-color: var(--colors-color-12, #fff);
  display: flex;
  flex-direction: column;
`;

const Div2 = styled.div`
  background-color: #0e8ad7;
  display: flex;
  width: 100%;
  align-items: center;
  justify-content: space-between;
  gap: 20px;
  padding: 12px 16px;
  @media (max-width: 991px) {
    max-width: 100%;
    flex-wrap: wrap;
  }
`;

const Div3 = styled.div`
  color: var(--colors-color-8, #323238);
  margin: auto 0;
  font: 500 16px/19px SF Pro Display, -apple-system, Roboto, Helvetica,
    sans-serif;
`;

const Div4 = styled.div`
  align-self: stretch;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 5px;
  @media (max-width: 991px) {
    justify-content: center;
  }
`;

const Img = styled.img`
  aspect-ratio: 1.38;
  object-fit: contain;
  object-position: center;
  width: 18px;
  opacity: 0.56;
  overflow: hidden;
  max-width: 100%;
  margin: auto 0;
`;

const Img2 = styled.img`
  aspect-ratio: 1;
  object-fit: contain;
  object-position: center;
  width: 17px;
  opacity: 0.56;
  overflow: hidden;
  align-self: stretch;
  max-width: 100%;
`;

const Img3 = styled.img`
  aspect-ratio: 0.53;
  object-fit: contain;
  object-position: center;
  width: 9px;
  opacity: 0.56;
  overflow: hidden;
  align-self: stretch;
  max-width: 100%;
`;

const Div5 = styled.div`
  color: var(--colors-color-12, #fff);
  align-items: start;
  background-color: #1da1f2;
  width: 100%;
  padding: 20px 16px;
  font: 500 18px/21px Roboto, sans-serif;
  @media (max-width: 991px) {
    max-width: 100%;
  }
`;

const Div6 = styled.div`
  border-radius: 4px;
  border: 1px solid var(--colors-color-10, #e5e5e5);
  align-self: center;
  display: flex;
  margin-top: 24px;
  width: 396px;
  flex-direction: column;
  align-items: start;
  padding: 8px 0;
`;

const Div7 = styled.div`
  display: flex;
  width: 160px;
  max-width: 100%;
  gap: 12px;
  padding: 0 20px;
`;

const Img4 = styled.img`
  aspect-ratio: 1;
  object-fit: contain;
  object-position: center;
  width: 24px;
  overflow: hidden;
  max-width: 100%;
`;

const Div8 = styled.div`
  color: #323238;
  align-self: center;
  white-space: nowrap;
  margin: auto 0;
  font: 400 16px/20px Roboto, sans-serif;
  @media (max-width: 991px) {
    white-space: initial;
  }
`;

const Div9 = styled.div`
  border-radius: 4px;
  border: 1px solid var(--colors-color-10, #e5e5e5);
  align-self: center;
  display: flex;
  margin-top: 23px;
  width: 100%;
  max-width: 396px;
  justify-content: space-between;
  gap: 20px;
  padding: 8px;
`;

const Div10 = styled.div`
  display: flex;
  justify-content: space-between;
  gap: 12px;
  padding: 0 20px;
`;

const Img5 = styled.img`
  aspect-ratio: 1;
  object-fit: contain;
  object-position: center;
  width: 24px;
  overflow: hidden;
  max-width: 100%;
`;

const Div11 = styled.div`
  color: #323238;
  align-self: center;
  white-space: nowrap;
  margin: auto 0;
  font: 400 16px/20px Roboto, sans-serif;
  @media (max-width: 991px) {
    white-space: initial;
  }
`;

const Img6 = styled.img`
  aspect-ratio: 1;
  object-fit: contain;
  object-position: center;
  width: 20px;
  overflow: hidden;
  align-self: center;
  max-width: 100%;
  margin: auto 0;
`;

const Div12 = styled.div`
  align-items: center;
  align-self: center;
  display: flex;
  margin-top: 23px;
  width: 100%;
  max-width: 396px;
  gap: 16px;
  padding: 0 20px;
  @media (max-width: 991px) {
    justify-content: center;
  }
`;

const Div13 = styled.div`
  border-radius: 4px;
  border: 1px solid var(--colors-color-10, #e5e5e5);
  align-self: stretch;
  display: flex;
  justify-content: space-between;
  gap: 10px;
  padding: 8px 0;
`;

const Img7 = styled.img`
  aspect-ratio: 1;
  object-fit: contain;
  object-position: center;
  width: 24px;
  overflow: hidden;
  max-width: 100%;
`;

const Div14 = styled.div`
  color: var(--colors-color-8, #323238);
  align-self: center;
  white-space: nowrap;
  margin: auto 0;
  font: 400 14px/20px Roboto, sans-serif;
  @media (max-width: 991px) {
    white-space: initial;
  }
`;

const Img8 = styled.img`
  aspect-ratio: 1;
  object-fit: contain;
  object-position: center;
  width: 20px;
  overflow: hidden;
  max-width: 100%;
  margin: auto 0;
`;

const Div15 = styled.div`
  border-radius: 4px;
  border: 1px solid var(--colors-color-10, #e5e5e5);
  align-self: stretch;
  display: flex;
  justify-content: space-between;
  gap: 10px;
  padding: 8px 0;
`;

const Img9 = styled.img`
  aspect-ratio: 1;
  object-fit: contain;
  object-position: center;
  width: 24px;
  overflow: hidden;
  max-width: 100%;
`;

const Div16 = styled.div`
  color: var(--colors-color-7, #949c9e);
  align-self: center;
  white-space: nowrap;
  margin: auto 0;
  font: 400 14px/20px Roboto, sans-serif;
  @media (max-width: 991px) {
    white-space: initial;
  }
`;

const Div17 = styled.div`
  border-top: 2px solid var(--colors-color-6, #f2f2f2);
  background-color: var(--colors-color-5, #fff);
  display: flex;
  margin-top: 572px;
  width: 100%;
  justify-content: space-between;
  gap: 16px;
  padding: 12px 16px 12px 80px;
  @media (max-width: 991px) {
    max-width: 100%;
    margin-top: 40px;
    flex-wrap: wrap;
    padding-left: 20px;
  }
`;

const Div18 = styled.div`
  color: var(--blue-light-blue-light-1, #1da1f2);
  white-space: nowrap;
  border-radius: 6px;
  background-color: var(--blue-light-blue-light-3, #edf8ff);
  aspect-ratio: 1.825;
  align-items: start;
  padding: 15px;
  font: 500 14px/16px Roboto, sans-serif;
  @media (max-width: 991px) {
    white-space: initial;
  }
`;

const Div19 = styled.div`
  display: flex;
  aspect-ratio: 1.825;
  flex-direction: column;
`;

const Div20 = styled.div`
  color: var(--colors-color-12, #fff);
  text-align: center;
  white-space: nowrap;
  border-radius: 6px;
  background-color: var(--colors-color-1, #1da1f2);
  aspect-ratio: 1.825;
  align-items: center;
  padding: 15px 20px;
  font: 500 14px/16px Roboto, sans-serif;
  @media (max-width: 991px) {
    white-space: initial;
  }
`;
